# Configuration du plugin ProceduralDungeons
# Version: 1.0.0
# Développé par: Arkoter
# GitHub: https://github.com/Arkoter/ProceduralDungeons

# ================================
# PARAMÈTRES DES DONJONS
# ================================
dungeon:
  # Taille maximale d'un donjon (en blocs)
  max-size: 100

  # Taille minimale d'un donjon (en blocs)
  min-size: 30

  # Difficulté maximale autorisée
  max-difficulty: 10

  # Difficulté par défaut lors de la création
  default-difficulty: 1

  # Taille par défaut lors de la création
  default-size: 50

  # Hauteur des murs du donjon
  wall-height: 4

  # Matériau des sols
  floor-material: STONE_BRICKS

  # Matériau des murs
  wall-material: COBBLESTONE

  # Matériau des salles spéciales
  special-room-material: POLISHED_ANDESITE

# ================================
# PARAMÈTRES DU LOOT
# ================================
loot:
  # Chance de base de trouver des diamants (%)
  diamond-chance: 20

  # Chance de base d'objets rares (%)
  rare-item-chance: 15

  # Chance d'obtenir une clé de boss dans un coffre (%)
  boss-key-chance: 25

  # Multiplicateur de loot basé sur la difficulté
  difficulty-multiplier: 1.5

  # Nombre minimum de coffres par donjon
  min-chests-per-dungeon: 3

  # Nombre maximum de coffres par donjon
  max-chests-per-dungeon: 8

# ================================
# PARAMÈTRES DES BOSS
# ================================
boss:
  # Multiplicateur de vie des boss selon la difficulté
  health-multiplier: 1.5

  # Multiplicateur d'expérience des boss
  experience-multiplier: 2.0

  # Types de boss selon la difficulté
  boss-types:
    1: ZOMBIE
    2: SKELETON
    3: WITHER_SKELETON
    4: BLAZE
    5: WITHER

  # Bonus de loot pour les boss (multiplicateur)
  loot-bonus-multiplier: 3.0

# ================================
# PARAMÈTRES DES PIÈGES
# ================================
traps:
  # Dégâts infligés par les pièges de base
  damage: 2.0

  # Multiplicateur de dégâts selon la difficulté
  damage-multiplier: 1.2

  # Nombre minimum de pièges par donjon
  min-traps-per-dungeon: 5

  # Nombre maximum de pièges par donjon
  max-traps-per-dungeon: 20

  # Pourcentage de pièges par rapport à la taille du donjon
  trap-density: 0.15

  # Durée de l'effet poison (en ticks, 20 ticks = 1 seconde)
  poison-duration: 200

  # Niveau de l'effet poison
  poison-level: 1

# ================================
# PARAMÈTRES DE GÉNÉRATION
# ================================
generation:
  # Pourcentage d'ouvertures supplémentaires dans le labyrinthe
  extra-connections: 0.01

  # Nombre de salles spéciales par donjon
  special-rooms:
    min: 3
    max: 6

  # Taille des salles spéciales
  room-size:
    min: 5
    max: 9

  # Taille de la salle du boss
  boss-room-size: 12

  # Seed aléatoire pour la génération (0 = aléatoire)
  seed: 0

# ================================
# PARAMÈTRES DE PERFORMANCE
# ================================
performance:
  # Délai de génération entre chaque chunk (en millisecondes)
  generation-delay: 50

  # Nombre maximum de donjons actifs simultanément
  max-active-dungeons: 10

  # Temps d'inactivité avant nettoyage automatique (en millisecondes)
  cleanup-threshold: 3600000 # 1 heure

  # Intervalle de sauvegarde automatique (en secondes)
  auto-save-interval: 300 # 5 minutes

# ================================
# PARAMÈTRES D'EXPÉRIENCE
# ================================
experience:
  # Bonus d'expérience pour tuer des monstres dans un donjon
  monster-kill-bonus: 1.5

  # Bonus d'expérience pour compléter un donjon
  completion-bonus: 100

  # Bonus d'expérience selon la difficulté
  difficulty-bonus: 50

# ================================
# PARAMÈTRES DE DEBUG
# ================================
debug:
  # Activer les messages de debug
  enabled: false

  # Afficher les informations de génération
  show-generation-info: false

  # Afficher les statistiques de performance
  show-performance-stats: false

# ================================
# PARAMÈTRES AVANCÉS
# ================================
advanced:
  # Utiliser la génération asynchrone
  async-generation: true

  # Précharger les chunks du donjon
  preload-chunks: true

  # Limiter le nombre de monstres dans un donjon
  max-monsters-per-dungeon: 50

  # Respawn automatique des monstres
  monster-respawn: true

  # Délai de respawn des monstres (en secondes)
  monster-respawn-delay: 300

# ================================
# PARAMÈTRES DE LIMITES
# ================================
limits:
  # Nombre maximum de donjons par joueur
  max-dungeons-per-player: 5

  # Nombre maximum de joueurs par donjon
  max-players-per-dungeon: 10

  # Cooldown entre créations de donjon (en secondes)
  creation-cooldown: 60

  # Mondes où la création est autorisée (vide = tous)
  allowed-worlds: []

# ================================
# PARAMÈTRES DE THÈMES
# ================================
themes:
  # Activer les thèmes personnalisés
  enabled: true

  # Thèmes disponibles et leurs matériaux
  medieval:
    floor: STONE_BRICKS
    wall: COBBLESTONE
    decoration: STONE

  nether:
    floor: NETHER_BRICKS
    wall: BLACKSTONE
    decoration: MAGMA_BLOCK

  ocean:
    floor: PRISMARINE
    wall: DARK_PRISMARINE
    decoration: SEA_LANTERN

  desert:
    floor: SANDSTONE
    wall: SMOOTH_SANDSTONE
    decoration: CHISELED_SANDSTONE

  ice:
    floor: PACKED_ICE
    wall: BLUE_ICE
    decoration: ICE

  end:
    floor: END_STONE_BRICKS
    wall: END_STONE
    decoration: PURPUR_BLOCK

  jungle:
    floor: MOSSY_STONE_BRICKS
    wall: JUNGLE_LOG
    decoration: JUNGLE_LEAVES

  steampunk:
    floor: IRON_BLOCK
    wall: COPPER_BLOCK
    decoration: REDSTONE_LAMP

# ================================
# PARAMÈTRES D'ÉCONOMIE (OPTIONNEL)
# ================================
economy:
  # Activer l'intégration économique
  enabled: false

  # Coût de création d'un donjon
  creation-cost: 1000

  # Coût par bloc de taille supplémentaire
  size-cost-per-block: 10

  # Récompense pour compléter un donjon
  completion-reward: 500

# ================================
# PARAMÈTRES DE SAUVEGARDE
# ================================
backup:
  # Activer les sauvegardes automatiques
  enabled: true

  # Intervalle entre les sauvegardes (en minutes)
  interval: 30

  # Nombre de sauvegardes à conserver
  keep-backups: 5

  # Compresser les sauvegardes
  compress: true

# ================================
# NOTIFICATIONS ET MESSAGES
# ================================
notifications:
  # Activer les notifications en temps réel
  enabled: true

  # Afficher les messages de progression
  show-progress: true

  # Afficher les statistiques en fin de donjon
  show-completion-stats: true

  # Notifications pour les autres joueurs
  broadcast-achievements: true

# ================================
# COMPATIBILITÉ AVEC D'AUTRES PLUGINS
# ================================
compatibility:
  # WorldGuard - Respecter les régions protégées
  worldguard: true

  # PlotSquared - Intégration avec les parcelles
  plotsquared: false

  # McMMO - Intégration avec les compétences
  mcmmo: true

  # Vault - Intégration économique
  vault: false

# ================================
# PARAMÈTRES EXPÉRIMENTAUX
# ================================
experimental:
  # Nouvelles fonctionnalités en test
  # (À utiliser à vos risques et périls)

  # Génération procédurale avancée
  advanced-generation: false

  # IA pour les boss
  smart-boss-ai: false

  # Donjons multi-étages
  multi-level-dungeons: false